### ISSUE TITLE
Osa 04_1.4 - Joku taisi yhden sanan

### ISSUE THREAD

**Issue by HWMarttinen** [materiaalit/ohjelmointi-s18#10]
Osan 4 kappaleessa 1.4. Monimutkaisemman tiedon lukeminen on lause, josta tuntuu puuttuvan sana.

"Alla tiedon lukemisesta on esitelty muoto, missä tietoa **[kysytään?]** osa kerrallaan."

Sana kysytään on minun ehdotukseni, se puuttuu alkuperäisestä.

**Comment by avihavai** [comment]
Korjattu, kiitos! :+1:
