### ISSUE TITLE
Tehtävän 1-37 Syötteiden rajaus tarkistusongelma

### ISSUE THREAD

**Issue by JoonaSar** [materiaalit/ohjelmointi-s18#2]
Sekä localin että serverin tarkistus antaa seuraavan virheen, vaikka todellisuudessa koodi antaa vain viisi kertaa "Syötä luku"-tekstin:

> "Syötä luku"-tekstejä pitäisi olla yhteensä 5 kertaa. Nyt kertoja oli 6 expected:<5> but was:<6>

Pajaohjaaja paikansi virheen testikoodin riville 52, missä split jakaa tekstin siten, että tyhjä osuus ennen ensimmäistä "Syötä luku"-tekstiä lasketaan mukaan.

**Comment by avihavai** [comment]
Kiitos paljon! Kyse oli tässä loppujenlopuksi niinkin pienestä asiasta kyse kuin kaksoispisteen olemassaolosta tuon Syötä luku -tekstin jälkeen, olipa vaikea korjata :). Korjasin testit "kiltimmiksi" tulevia sukupolvia varten ja ajoin palautettujen tehtävien testit uudelleen, eli tästä on nyt pisteet kirjattuna.
