### ISSUE TITLE
Väärä ohjekommentti tehtävässä 03_09

### ISSUE THREAD

**Issue by HWMarttinen** [materiaalit/ohjelmointi-s18#6]
Tehtävässä Osa03_09 "ListanSuurinLuku.java" on kommentti, jossa lukee
"// toteuta listan lukujen summan laskeminen tänne".

Tehtävässä on kyse listan pienimmän luvun etsimisestä, joten kyseinen kommentti taitaa olla eksynyt mukaan toisesta paikasta. TMC-esimerkkiratkaisussa on oikean näköinen kommentti
"// toteuta listan suurimman luvun selvittäminen tänne".

Eihän tällä ole mitään käytännön merkitystä, mutta pieni kielivirhe kumminkin.

**Comment by avihavai** [comment]
Tämä on korjattu; tulee korjattuna niille, ketkä lataavat tehtävän TMC:stä uudestaan. Kiitos!
