### ISSUE TITLE
Typo osan 3 kohdassa 3.2?

### ISSUE THREAD

**Issue by HWMarttinen** [materiaalit/ohjelmointi-s18#9]
Osan 3 kappaleessa 3.2 selitetään taulukon toimintaa, ja esimerkissä lukee:

"Taulukon läpikäynti loppuu kun muuttujan toistolauseen ehtolause indeksi < luvut.length on totta, eli kun indeksimuuttujan arvo on suurempi tai yhtäsuuri kuin taulukon pituus. "

Onko tämä oikein, vai onko teksti kirjoitettu käänteisesti? Pitäisikö sen olla jotakuinkin "taulukon läpikäynti loppuu, kun muuttujan toistolause ei ole enää totta" jne.?

**Comment by avihavai** [comment]
Korjattu, kiitos! :+1:
